// Database types are auto-generated by Prisma
// These are additional frontend types

export type ExamType = 'SPEAKING' | 'WRITING';
export type QuestionFormat = 'AUDIO_ONLY' | 'PICTURE_TEXT' | 'VIDEO' | 'TEXT_ONLY';

export interface SpeakingQuestionWithMedia {
  id: string;
  examId: string;
  order: number;
  format: QuestionFormat;
  text: string;
  mediaUrl: string | null;
  timestamp: number | null;
  instructions: string | null;
}

export interface WritingPromptWithDetails {
  id: string;
  examId: string;
  order: number;
  title: string;
  prompt: string;
  wordLimit: number | null;
  timeLimit: number | null;
  instructions: string | null;
}

export interface ExamSessionWithDetails {
  id: string;
  examId: string;
  studentName: string;
  unlockCode: string;
  startedAt: Date;
  completedAt: Date | null;
  aiCodeUsed: string | null;
  isAiGraded: boolean;
  isManuallyGraded: boolean;
  exam: {
    id: string;
    title: string;
    type: ExamType;
  };
  speakingAnswers: Array<{
    id: string;
    questionId: string;
    audioUrl: string | null;
    transcription: string | null;
    question: SpeakingQuestionWithMedia;
  }>;
  writingAnswers: Array<{
    id: string;
    promptId: string;
    content: string;
    lastSavedAt: Date;
    prompt: WritingPromptWithDetails;
  }>;
  aiGrades: Array<{
    id: string;
    summary: string;
    feedback: string;
    score: number | null;
  }>;
}

// Frontend state types
export interface StudentAnswerState {
  questionId: string;
  audioBlob: Blob | null;
  transcription: string;
  recordedAt: string;
}

export interface WritingAnswerState {
  promptId: string;
  content: string;
  lastSavedAt: string;
  wordCount: number;
}
